FROM node:lts-alpine

ARG TARGET_ENV

# install simple http server for serving static content
RUN npm install -g http-server

# make the 'app' folder the current working directory
WORKDIR /app

# copy both 'package.json' and 'package-lock.json' (if available)
COPY package*.json ./

# install project dependencies leaving out dev dependencies
RUN npm install --production

# copy project files and folders to the current working directory (i.e. 'app' folder)
COPY . .

# build app for different env
RUN npm run build-${TARGET_ENV}

EXPOSE 8080
CMD [ "http-server", "dist" ]